apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deployment
  namespace: drupal-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: hamza701/drupal-mysql-ci-cd:drupal-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      # imagePullSecrets:
      # - name: myregistrykey